language: node_js
node_js:
- node
- lts/*
script: gulp test
before_install:
- mkdir -p .npm
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
notifications:
  slack:
    secure: Bu3OZ0Cdy8eq0IMoLJmadDba8Yyb9ajobKocfp8V7/vfOjpIVXdFrGMqfckkZ22uiWxHCsYEX1ahQ77zTjbO3tNq1CTmSgEAWaqqMVz1iIVNhSoeHRfYDa9r1sKFpJv1KEz+j/8i2phcR5MDE6cGK+byJmjfjcnkP1XoNiupuck=
before_deploy:
  - gulp build
deploy:
  provider: npm
  email: npm@stellar.org
  api_key:
    secure: Yb6nOoNeRCfNaah/R9fbT7n/6QTua5DWEDn0vMSEBWgmkviVsVyA2eTVs9895C9eFCRvdWBkQ92qE5ET5Lvp/KeYVuyxZIzpdWSqonSp74xrWm4W87F/4Lp+uDucfr+v9UfIl2uR9U9u90j+qiDfw8X5KNELiHrhY6xUCjoshsM=
  skip_cleanup: true
  on:
    tags: true
    repo: stellar/js-xdr
    branch: master
